openapi: 3.1.0
info:
  title: GlycamWeb Build Via URL API Documentation
  version: 1.0.0
servers:
- url: https://
paths:
  /glycam.org/url/condensed/{sequence}:
    get:
      operationId: get_glycam_org_url_condensed_sequence
      summary: Build Structure via URL
      description: Builds carbohydrate structures using the condensed glycam notation
        passed through the URL.
      parameters:
      - name: sequence
        in: path
        required: true
        schema:
          type: string
        description: The sequence of the sugar in condensed glycam notation.
        example: DManpa1-2DManpa1-3DManpa1-6[DManpa1-3]DManpb1-4DGlcpNAcb1-4DGlcpNAcb1-OH
      responses:
        '200':
          description: Success
