model_list:
  - model_name: "gpt-4o"
    litellm_params:
      model: "gpt-4o"
      api_key: ""
      max_retries: 5


general_settings:
  master_key: "sk-litellm-master-key-123"
  drop_params: true
  set_verbose: false
  default_litellm_params:
    timeout: 300  # 5 minute timeout
    max_retries: 5
    retry_interval: 60  # Wait 1 minute between retries
