openapi: 3.1.0
info:
  title: API Documentation for https://emojihub.yurace.pro
  version: 1.0.0
servers:
- url: https://emojihub.yurace.pro
paths:
  /api/random:
    get:
      operationId: get_api_random
      summary: Get Random Emoji
      description: Retrieves a random emoji from the database.
      parameters: []
      responses:
        '200':
          description: Success
  /api/all:
    get:
      operationId: get_api_all
      summary: Get All Emojis
      description: Retrieves an array of all emojis.
      parameters: []
      responses:
        '200':
          description: Success
  /api/all/category/{category-name}:
    get:
      operationId: get_api_all_category_category_name
      summary: Get Emojis by Category
      description: Retrieves emojis filtered by a specific category.
      parameters:
      - name: category-name
        in: path
        required: true
        schema:
          type: string
        description: The name of the category to filter emojis by.
        example: food-and-drink
      responses:
        '200':
          description: Success
  /api/all/group/{group-name}:
    get:
      operationId: get_api_all_group_group_name
      summary: Get Emojis by Group
      description: Retrieves emojis filtered by a specific group.
      parameters:
      - name: group-name
        in: path
        required: true
        schema:
          type: string
        description: The name of the group to filter emojis by.
        example: animal-bird
      responses:
        '200':
          description: Success
