openapi: 3.1.0
info:
  title: GLYCAM-Web JSON API Documentation
  version: 1.0.0
servers:
- url: http://
paths:
  /missing:
    post:
      operationId: post_missing
      summary: Build 3D Structure
      description: Generates a 3D structure for a sequence, with options for conformers.
      parameters:
      - name: sequence
        in: query
        required: true
        schema:
          type: string
        description: The sequence for which to build the 3D structure.
        example: DManpa1-6DManpa1-OH
      - name: buildOptions
        in: query
        required: false
        schema:
          type: object
        description: Options for building the 3D structure, such as number of conformers.
        example:
          conformers: 64
      responses:
        '200':
          description: Success
  /json/project_status/sequence/{str{pUUID}}/:
    get:
      operationId: get_json_project_status_sequence_strpUUID
      summary: Poll Project Status
      description: Checks the status of the default structure build for a project.
      parameters:
      - name: pUUID
        in: path
        required: true
        schema:
          type: string
        description: The project UUID to check the status for.
        example: 3c368bf2-ad73-43f3-a18d-d7d2dc11cf28
      responses:
        '200':
          description: Success
  /json/build_status/{str{pUUID}}/{str{conformerID}}/:
    get:
      operationId: get_json_build_status_strpUUID_strconformerID
      summary: Poll Specific Build Status
      description: Checks the status of a specific conformer build.
      parameters:
      - name: pUUID
        in: path
        required: true
        schema:
          type: string
        description: The project UUID to check the status for.
        example: 3c368bf2-ad73-43f3-a18d-d7d2dc11cf28
      - name: conformerID
        in: path
        required: true
        schema:
          type: string
        description: The conformer ID to check the status for.
        example: 1ogg
      responses:
        '200':
          description: Success
  /json/download/sequence/cb/{pUUID}/:
    get:
      operationId: get_json_download_sequence_cb_pUUID
      summary: Download Structure
      description: Downloads the minimized PDB file for a structure.
      parameters:
      - name: pUUID
        in: path
        required: true
        schema:
          type: string
        description: The project UUID for the structure to download.
        example: 3c368bf2-ad73-43f3-a18d-d7d2dc11cf28
      responses:
        '200':
          description: Success
